# Generated by Django 4.2.7 on 2023-12-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
    ]
